server:
    port: 8080
spring:
  jackson:
#    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd
    time-zone: GMT+8     
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
#      additional-paths: src/main/java,src/main/resources/templates,src/main/resources/**
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/oldtoys?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
mybatis:
  type-aliases-package: com.github.oldtoys.dict.domain,com.github.oldtoys.gen.domain
  mapper-locations: classpath:mapper/*.xml 
#  configuration: 
#    map-underscore-to-camel-case: true  ##开启驼峰
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql 


logging:
  level.root: info
  level.com.github.oldtoys: debug
    